Model subclass: #MyAgenda2
	instanceVariableNames: 'varFileName varItemCategories varCategoryItems varCategoryItems1 varCategories1 varCategories2 varItems2 varItems2ListSelectedIndex varCategories4 varCategories5 varCategoriesSelected varOrCategories varNotCategories varInstancesDictionary varFileNameText varCategories1ListLabels varAndCategoriesListLabels varNotCategoriesListLabels varItems2ListLabels varCategories4ListLabels varCategories5ListLabels varCategories1List varAndCategoriesList varNotCategoriesList varItems2List varCategories4List varCategories5List varDbConnection'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MyAgenda2'!
!MyAgenda2 commentStamp: 'mva 3/30/2016 17:11' prior: 0!
Personal Organizer. Stage One: Bookmark Manager.

	MyAgenda2 openBrowser.

	askAndCategories
	askNotCategories

	askCategories1
	askItems2
	askCategories4
	askCategories5
!

