Model subclass: #MyAgenda2
	instanceVariableNames: 'varFileName varItemCategories varCategoryItems varCategoryItems1 varCategories1 varCategories2 varItems2 varItems2ListSelectedIndex varCategories4 varCategories5 varCategoriesSelected varOrCategories varNotCategories varInstancesDictionary varFileNameText'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MyAgenda2'!
!MyAgenda2 commentStamp: 'mva 3/17/2016 18:04' prior: 0!

	MyAgenda2 openBrowser.

	askAndCategories
	askNotCategories

	askCategories1
	askItems2
	askCategories4
	askCategories5
!
